import { fileURLToPath } from 'node:url'
import { resolve } from 'node:path'
import { createHash } from 'node:crypto'
import { TourStore } from './store.ts'
import { startHttp } from './http.ts'
import { renderTour } from './render.ts'
const root = fileURLToPath(new URL('../..', import.meta.url))
const store = new TourStore(resolve(root, 'mcp/artifacts/smoke'))
const project = await store.open(resolve(root, 'frontend/src/graph/fixtures/sherlock.graph.json'))
// Synthetic reading rank for this developer fixture; real tours require algo output.
project.snapshot.readingSequence = [{ entityId: 'sherlock_project/notify.py', entityType: 'file', fileId: 'sherlock_project/notify.py', fileRank: 1, localRank: null, scores: { pagerank: null, betweenness: null, combined: null } }]
project.hash = createHash('sha256').update(JSON.stringify(project.snapshot)).digest('hex')
const draft = await store.create(project.id, 'Sherlock code tour — smoke test', 'ko', [
  { nodeId: 'root', caption: '저장소 전체 구조입니다.', transitionMs: 0, holdMs: 2000 },
  { nodeId: 'file:sherlock_project/notify.py', caption: 'notify.py 파일과 분석 근거를 확인합니다.', transitionMs: 1000, holdMs: 2000 },
  { nodeId: 'class:sherlock_project/notify.py::QueryNotify', caption: 'QueryNotify 클래스의 구조입니다.', transitionMs: 1000, holdMs: 2000 },
  { nodeId: 'root', caption: '전체 구조로 돌아왔습니다.', transitionMs: 1000, holdMs: 2000 },
])
// Smoke fixture is generated by the developer, never approves a real user's draft.
const http = await startHttp(store, resolve(root, 'frontend/dist'))
const session = http.registerRender(draft)
try {
  const output = await renderTour(draft, session.url, store.outputRoot, (frame, total) => {
    if (frame % 60 === 0) console.error(`${frame}/${total} frames`)
  })
  console.log(output)
} finally { session.dispose(); await http.close() }
